export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center px-6">
      <div className="w-full max-w-md text-center">
        <h1 className="text-5xl font-bold tracking-tight" style={{ color: '#28A0F0' }}>
          TapPay
        </h1>
        <p className="mt-3 text-text-secondary text-sm">
          One-tap crypto payments at the till.
          <br />
          NFC tap → pay in 2 seconds.
        </p>

        <div className="mt-10 flex flex-col gap-3">
          <p className="text-text-muted text-xs">
            Payment links are generated by merchants and include both address and order ID.
            <br />
            Format: <code className="text-text-secondary">/pay?m=&lt;merchant&gt;&amp;o=&lt;orderId&gt;</code>
          </p>
        </div>

        <p className="mt-10 text-text-muted text-xs">
          Are you a merchant? Generate an order from your terminal and tap a phone to collect.
        </p>
      </div>
    </main>
  );
}
